version: '3'
services:
  app:
    build: ./app
    expose:
      - "3030"
    volumes:
      - ./app:/usr/src/app
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - mynetwork

  web:
    image: httpd:2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/usr/local/nginx/conf/nginx.conf
      - ./uwsgi_params:/usr/local/apache2/conf/uwsgi_params
      - ./ssl/server.crt:/usr/local/apache2/conf/ssl/server.crt
      - ./ssl/server.key:/usr/local/apache2/conf/ssl/server.key
      - ./app:/usr/src/app
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
