version: '3'
services:
  app:
    build: ./app
    #build:
    #  context: .
    #  dockerfile: Dockerfile-web
    #ports:
    #  - "3030:3030"
    expose:
      - "3030"
    volumes:
      - ./app:/usr/src/app
    #working_dir: /app
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - mynetwork
    #command: bash -c "pip install -r requirements.txt && python main.py"

  web:
    image: httpd:2.4
    #build:
    #  context: .
    #  dockerfile: Dockerfile-apache
    ports:
      - "80:80"
      - "443:443"
     # - "3030:3030"
    volumes:
    #  - ./default.conf:/usr/local/nginx/conf/nginx.conf
    #  - ./data/html:/var/www/html
      - ./uwsgi_params:/usr/local/apache2/conf/uwsgi_params
      - ./ssl/server.crt:/usr/local/apache2/conf/ssl/server.crt
      - ./ssl/server.key:/usr/local/apache2/conf/ssl/server.key
      - ./app:/usr/src/app
    depends_on:
      - app
    networks:
      - mynetwork
    #environment:
     # - SERVER_NAME=localhost

networks:
  mynetwork:
